version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/zapclick
      - JWT_SECRET=seu_jwt_secret_aqui
      - HOTMART_CLIENT_ID=seu_client_id_aqui
      - HOTMART_CLIENT_SECRET=seu_client_secret_aqui
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 